### ISSUE TITLE
g++: error: .`pkg-config:  There is no file or directory

### ISSUE THREAD

**Issue by brunodiazu** [hebaishi/linter-gcc#102]
-c -Wall `pkg-config --cflags --libs gtk+-3.0`

How to add the GTK+ libraries to Atom?

![image](https://cloud.githubusercontent.com/assets/17410747/21940612/de6ed644-d9a3-11e6-858d-fa66d315ec42.png)

![image](https://cloud.githubusercontent.com/assets/17410747/21940628/f498300a-d9a3-11e6-9199-842428ecef7e.png)

In the package "Gcc-Make-run" everything's fine :c

**Comment by hebaishi** [comment]
You don't need the gtk libraries for linter-gcc because linting is performed at the level of the individual translation unit. You can simply remove the ```pkg-config``` stuff from your compile command, and as long as your headers can be found, linter-gcc should work.
