### ISSUE TITLE
GCC error

### ISSUE THREAD

**Issue by GioValca** [hebaishi/linter-gcc#103]
<img width="609" alt="schermata 2017-01-14 alle 19 50 31" src="https://cloud.githubusercontent.com/assets/25123294/21957253/e46e7596-da92-11e6-95a4-fd2d329de8b8.png">

**Comment by hebaishi** [comment]
Looks like you are using clang (the default C/C++ compiler on OSX) and not GCC. I suggest you look [here](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues)
