### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by hhhaiai** [hebaishi/linter-gcc#126]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta3 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /Users/sanbo/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
simplified-chinese-menu 3.5.0 
autocomplete-java 1.2.5 
gcc-make-run 0.2.9 
gpp-compiler 3.0.7 
java-generator 2.2.3 
java-importer 1.4.1 
linter-gcc 0.7.1 
```

**Comment by Fsmash** [comment]
You probably need to install dependencies. That fixed it for me. Install the linter and linter-ui-default package.

**Comment by guidol** [comment]
How can I install the dependencies?? could you let me know??

**Comment by thegoldgoat** [comment]
@guidol 
Install the dependencies inside Atom by searching for linter and linter-ui-default, or you can install them with the terminal installer:
`apm install linter`
`apm install linter-ui-default`

**Comment by gaoljhy** [comment]
wow,easy

**Comment by hhhaiai** [comment]
thx

**Comment by leofishman** [comment]
thanks!!!
