### ISSUE TITLE
clang -cc1as: error

### ISSUE THREAD

**Issue by SuperChenSSS** [hebaishi/linter-gcc#143]
I was using linter-gcc to check my grammar when suddenly an error came out, it said "clang -cc1as: error: unable to open output file '940e2052-aefd-48da-b619-2393bba52932.o': 'Permission denied' "
The message looks like this:
![image](https://user-images.githubusercontent.com/17025439/30655991-2b1daa7a-9e65-11e7-9aed-d67185e0ed4b.png)
Could you please help me fix it?

**Comment by TianzeWang** [comment]
+1

**Comment by SuperChenSSS** [comment]
I came to the conclusion...
According to this case: #19 
All you have to do is add **-fsyntax-only** into the c++ flags
It should solve the problem
@TianzeWang
