### ISSUE TITLE
Not working in Windows 10 - followed evrything

### ISSUE THREAD

**Issue by ShakilAhmedShaj** [hebaishi/linter-gcc#158]
## Checklist
* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14
* [x] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

## Issue (including debugging messages):

I have followed every step from this link - https://github.com/hebaishi/linter-gcc/wiki/Windows-Users-Guide

This is my package settings -

![image](https://user-images.githubusercontent.com/15268903/35358264-322bc2ba-0180-11e8-9166-f0e6aa7fae30.png)

These are my windows path links -
![image](https://user-images.githubusercontent.com/15268903/35358279-450b9342-0180-11e8-8c97-724f3586e92d.png)

and this is my atom editor pic, its just blank

![image](https://user-images.githubusercontent.com/15268903/35358288-50d589bc-0180-11e8-8863-07d2ccf686fa.png)

and here is the g++ output - 

![image](https://user-images.githubusercontent.com/15268903/35426706-28149670-028f-11e8-9d09-123cdc1a84fc.png)

please help me ;-(

**Comment by DamSenViet** [comment]
It's a linter, not a terminal that you can run programs in. It's supposed to be blank if there are no ERRORS... linter-gcc does throw warnings from gcc's -Wall flag though.
If what you want is a program you can run c programs in, get platformio-ide-terminal and use the command line to compile and run.

**Comment by ShakilAhmedShaj** [comment]
I just given this terminal view to let u know that gcc is working, I dont want to run my code in terminal, my linter gcc is not working I mean its not running or showing any error.

**Comment by sweenish** [comment]
It is indeed broken on Windows 10, at least.

If I delete a semi-colon, the status bar will change to show one error and one warning, but when I pull up the panel, it's blank. After I add the semi-colon back, the status bar never changes. C:\MinGW\bin in the PATH (have rebooted as well), include directory setup as well (C:\MinGW\include), have tried using both /* and \* at the end, but it makes no difference. Have used it with Atom's built-in C++, and the language-cpp14 package, doesn't work with either one.

The linter is broke on Windows, and flaky at best on Linux.

On Windows, it has failed to work with mingw and MSYS2. Have not tried Cygwin, but if it doesn't work with those two, I don't see Cygwin working.

Would it stand a chance at working with the VS C++ libraries in the include path while still using g++ as the compiler? I'm leaning toward no, but I haven't tried that yet. VS Code is set up to lint using those libraries, but I always compile manually through the integrated bash terminal (Arch in my case).

**Comment by babingbaboom** [comment]
Same problem, the linter didn't seem to manage to produce anything.

**Comment by walnutwaldo** [comment]
I'm having the same problem.

**Comment by Filliny** [comment]
Same here- no errrors in dev console, no displaying errors in code... if it works - it works silent)

**Comment by Delran** [comment]
Linter GCC doesn't work anymore, [get LinterGCC2](https://atom.io/packages/linter-gcc2)
