### ISSUE TITLE
issue for syntax checking

### ISSUE THREAD

**Issue by jp-eagle** [hebaishi/linter-gcc#18]
##### Platform: `darwin`
---
I installed 
# atom 1.3.2
# linter 1.11.3
# linter-gcc 0.5.9 
# osx 10.11.2
# gcc
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

when I save my helloworld.c for linter to check the syntax, I got below error

errors=0'
error: unable open output file 'helloworld.o': 'Permission defied'
1 error generated.

I checked the command line in console, it is:
/usr/bin/gcc -c -Wall -std=gnu99 -fmax-errors=0 /myfolder/helloworld.c

I ran the command line in a terminal, helloword.o is generated in current folder.

this package was working in previous version of atom/linter/linter-gcc, but in this version it doesn't work.

could you check where did you set the default folder to compile the c program and from where do you read the .o file?

**Comment by hebaishi** [comment]
It looks like you are trying to create a file in your system root, and you generally don't have write permissions in that folder. Please try placing your C source file in your home directory (On OSX, that would be /Users/yourusername) and running linter-gcc again.

**Comment by jp-eagle** [comment]
thanks for your prompt reply.

yes, I created project folder out of my home folder, but I have permission to create a file inside.
when I use command line, the helloworld.o is created in /myfolder/helloworld.o

also, I tried to put .c file into my home folder. I got same issue. permission denied.

this folder structure works in previous version, but I didn't use them a few weeks. after I upgrade both atom/linter/linter-gcc a few times, it has the problem.
I also removed everything and re-installed atom and packages again. problem is still here.

**Comment by hebaishi** [comment]
Yes I think I know what the problem is. I have read online that if you are using XCode, running gcc actually runs clang instead of gcc. The easiest way to find out what you are actually running is to type ```which gcc``` into your terminal. Note that if you find out you are using clang, you are better off using the clang-linter found [here](https://atom.io/packages/linter-clang).

[This](http://stackoverflow.com/questions/19535422/os-x-10-9-gcc-links-to-clang) stackoverflow post has information about this issue and how to install the 'real' GCC.

**Comment by jp-eagle** [comment]
I just tried to revert back to previous linter-gcc version. 0.5.8 version working in my env. and 0.5.9 doesn't work.

let me try clang-linter also.

-rwxr-xr-x  1 root  wheel  18176 Dec  3 14:36 /usr/bin/gcc

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

**Comment by hebaishi** [comment]
Could you provide the output of the command: ```ls -laR /myfolder```

**Comment by jp-eagle** [comment]
looks it is due to a gcc preprocess option '-c' caused the issue. .o was not piped in for linter if use this option.
I don't have standard gcc to test. but by the main time, I will stay in 0.5.8 first for my work.

--------
see this:

jpe$ ls -laR /myfolder
total 32
drwxr-xr-x   4 jpe   wheel   136 Dec 22 01:11 .
drwxr-xr-x  36 root  wheel  1292 Dec 22 01:07 ..
-rwxr-xr-x   1 jpe   wheel  8432 Dec 22 01:11 a.out
-rw-r--r--   1 jpe   wheel    61 Dec 22 01:11 helloworld.c

**Comment by hebaishi** [comment]
Ok I will move that option into the configuration page, so the user has the option to turn it off if it causes problems for whatever reason.

**Comment by hebaishi** [comment]
Change has been pushed as an update. Could you please update linter-gcc to 0.5.10 to confirm it's working?

**Comment by jp-eagle** [comment]
yes, it works without '-c'
