### ISSUE TITLE
Relative execPath not working

### ISSUE THREAD

**Issue by csholmq** [hebaishi/linter-gcc#20]
Latest release (37dadcfad4fa537474889e9304f89619cbff6b0c) broke my relative build path I'm afraid.

`.gcc-flags.json`
```
{
  "execPath": "./Sw/P_XMC/tools/ARM-GCC/bin/arm-none-eabi-gcc",
  "gccDefaultCFlags": "-Wall",
  "gccDefaultCppFlags": "-Wall -std=c++11",
  "gccErrorLimit": 5,
  "gccIncludePaths": "Sw/A_XMC/out/obj",
  "gccSuppressWarnings": true
}
```

> linter-gcc: "./Sw/P_XMC/tools/ARM-GCC/bin/arm-none-eabi-gcc" not found

Win7, Atom 1.3.2, linter-gcc 0.5.11

**Comment by csholmq** [comment]
```
// Cross-platform $PATH expansion
command = require("shelljs").which(command);
```
yields null. 

Ugly workaround:

```
// Expand path if necessary
if (command.substring(0,1) == ".") {
    rawCommand = path.join(cwd, command);
}
// Cross-platform $PATH expansion
command = require("shelljs").which(rawCommand);
if (command == null) {
  command = rawCommand;
}
```

**Comment by hebaishi** [comment]
I've just tested the code and I have it working fine. When I have a project open, the ```./``` is expanded to the project root. When no project is open, ```./``` is simply the path to the currently open file.

**Comment by csholmq** [comment]
Turned out that I needed to append .exe to the execPath. 

`"execPath": "./Sw/P_XMC/tools/ARM-GCC/bin/arm-none-eabi-gcc.exe"` worked while `"execPath": "./Sw/P_XMC/tools/ARM-GCC/bin/arm-none-eabi-gcc"` didn't. Different behaviour it seems.
