### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by SobrancelhaDoDragao** [hebaishi/linter-gcc#205]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Linux Mint
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/eudson/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
  2x -3:00.2.0 welcome:show (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
color-picker 2.3.0 
file-icons 2.1.32 
linter-gcc 0.7.1 
pigments 0.40.2 
```

**Comment by Delran** [comment]
Linter GCC doesn't work anymore, https://atom.io/packages/linter-gcc2

**Comment by Arcanemagus** [comment]
See the following issue for further details and some potential resolutions.

**Comment by Arcanemagus** [comment]
Duplicate of #209
