### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by Joel-Costamagna** [hebaishi/linter-gcc#22]
when i save the file it shows this output : 
"errors=0'
error: unable to open output file: Permission denied"
1 error generated"
<img width="1046" alt="capture d ecran 2016-01-30 a 16 20 09" src="https://cloud.githubusercontent.com/assets/16178951/12696551/c0a55816-c76d-11e5-96ae-e47c1ae3f213.png">
i see in the terminal that the output file is not created.
how can i add the permission to create the file or make the error message invisible ?

**Comment by hebaishi** [comment]
Could you open the developer console and copy your linter-gcc command, then paste it here? You can access the console by pressing ```Ctrl+Shift+I``` or ```cmd+Shift+I``` and clicking console.

**Comment by Joel-Costamagna** [comment]
````
linter-gcc trying: /Users/joel/Documents/COURS/archi2/TD/.gcc-flags.json
main.js:142 linter-gcc: /usr/bin/clang -Wall -o "executable" -c -fmax-errors=0 /Users/joel/Documents/COURS/archi2/TD/simple.c
````
````
src/beautify.coffee [verbose]: save editor positions atom-beautify.language_c_beautify_on_save false Object {}
logger.coffee:60 src/beautify.coffee [verbose]: save editor positions atom-beautify.language_c_beautify_on_save false Object {}
````

**Comment by hebaishi** [comment]
You simply need to remove the ```-o "executable"``` option. You don't need to generate a compiled binary for linting. Also, since you are on OSX, it might be better if you used [linter-clang](https://atom.io/packages/linter-clang). Let me know if this fixes the problem for you.

**Comment by hebaishi** [comment]
Hello. Have you managed to get it working?

**Comment by Joel-Costamagna** [comment]
Yes thanks it works well with `linter-clang`
