### ISSUE TITLE
Linting with gfortran

### ISSUE THREAD

**Issue by Luthaf** [hebaishi/linter-gcc#30]
Would it be possible to lint fortran code using gfortran with this package? Would it make sense to incorporate fortran linting here, or to fork this package to create a fortran linter ?

**Comment by kepler0** [comment]
It only makes sense if you use the `gcc` or `g++` binaries to lint fortran.

**Comment by kepler0** [comment]
I think you might want to create a `linter-gfortran` package. Thankfully if the output syntax is the same as `gcc` you can reuse a lot of the code in this package, `linter-clang`, and `linter-emscriptem`

**Comment by hebaishi** [comment]
Yes I agree with @kepler0

**Comment by Luthaf** [comment]
> It only makes sense if you use the gcc or g++ binaries to lint fortran.

You would use the `gfortran` binary, but most of the code would be the same otherwise, because the ouptut and input syntax are the same.

> I think you might want to create a linter-gfortran package.

Yeah, that seems the way to go. I'll see if I find the time to do that!

**Comment by Luthaf** [comment]
Well, that was easier that what I tought! If anyone is interested, the package is here: https://atom.io/packages/linter-gfortran

**Comment by kepler0** [comment]
I love it. `linter-gfortran` based on `linter-gcc` based on `linter-clang`. :heart_eyes:
