### ISSUE TITLE
Join AtomLinter.

### ISSUE THREAD

**Issue by kepler0** [hebaishi/linter-gcc#31]
This is such a great package with such an active user base. Would you like to join us over at @AtomLinter?

Joining us would ensure that your package is maintained if you ever lose interest or just get busy with other projects. As well, making sure that this is kept up to date with any API changes or improvements.

/cc @steelbrain

**Comment by hebaishi** [comment]
Yes that sounds great! What do I need to do?

**Comment by kepler0** [comment]
We'll have to wait for @steelbrain or someone else with Admin privileges to invite you to join the organization, from there all it takes is transferring ownership to AtomLinter.

**Comment by hebaishi** [comment]
Awwww I feel like I'm giving up my baby now! I'm not so sure I want do this! :cry:
In all fairness, I love linter-gcc, and I love the user base. It's unlikely I'll ever stop working on it.

**Comment by kepler0** [comment]
No worries. It's all yours to decide. I still want to want you to join @AtomLinter, just so you may work closer with us though.

**Comment by hebaishi** [comment]
Yes I'm definitely up for that! :+1:

**Comment by steelbrain** [comment]
@hebaishi Can you please transfer the project to me so I can transfer it to the org? This way all of the links will keep working and update on APM will be just another update (ie. no unpublish + republish, just publish)

**Comment by hebaishi** [comment]
@steelbrain is there any way to do this without me giving away my baby? :sad:

**Comment by steelbrain** [comment]
@hebaishi You will still have admin rights over your repo, and you can trust me, I've done this a lot of times :)
GitHub's org permissions do not allow one to move their repo in unless they are an org owner, we can of course create an empty org in the repo where you can pull from this and push there, but then you'll have to unpublish and republish your package on apm

**Comment by hebaishi** [comment]
I'm sorry guys, but I'm not ready to give up ownership of the repo. Perhaps we can revisit this at some point in the future. In the meantime, I will continue to maintain linter-gcc.

**Comment by steelbrain** [comment]
Just a side note that I wasn't really going to take ownership, I was just going to act as a middle man to help you transfer your repo (which I do everytime somebody wants to do that). 

Created https://github.com/AtomLinter/linter-gcc and made you admin as an option 2 from https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository

**Comment by hebaishi** [comment]
@steelbrain can I keep my repo here, and work on other projects in the AtomLinter org, as @kepler0 suggested?

**Comment by steelbrain** [comment]
Whichever you prefer
