### ISSUE TITLE
Lint on the fly not working on Ubuntu

### ISSUE THREAD

**Issue by pankajk0001** [hebaishi/linter-gcc#32]
Please help me run lint on the fly as it is not working.I have just installed and enabled the linter.

**Comment by hebaishi** [comment]
* Are you getting any error?
* Do you have ```gcc``` installed? What output do you get from typing ```gcc --version``` in a terminal?
* Also, inside atom, could you press ```Ctrl+Shift+I``` , click console, copy the linter-gcc command that appears in there, and paste it here?

**Comment by pankajk0001** [comment]
Window load time: 4164ms
/usr/share/atom/resources/app.asar/src/text-editor-component.js:957 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/usr/share/atom/resources/app.asar/src/text-editor-component.js:957 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by pankajk0001** [comment]
this is what appears in console.
And Yes i Have the gcc installed

**Comment by hebaishi** [comment]
linter-gcc should print text to the console that starts with ```linter-gcc: ```. That is what we need. The messages you pasted here could have come from anywhere. Note that your text editor grammar should be set to C/C++/C++14, you need to have linting on-the-fly enabled, and linting is activated when the text in the current editor is modified.

**Comment by pankajk0001** [comment]
Test editor grammar is set to C attached file will show that
![screenshot from 2016-02-17 23 14 34](https://cloud.githubusercontent.com/assets/17299085/13118861/3d879468-d5cc-11e5-9243-57158a89dfca.png)

**Comment by hebaishi** [comment]
It looks like you don't have the base linter installed. This is an interesting problem, because when you install linter-gcc, linter should be installed automatically. Anyway, all you need to do is run the following command in your terminal, and restart atom.
```
apm install linter
```
Please let me know when you've got it working.

**Comment by pankajk0001** [comment]
Ok Let me Try this.

**Comment by pankajk0001** [comment]
Great its working.
Thanks
but bug should be fixed
linter should install automatically
make sure to fix the bug

**Comment by hebaishi** [comment]
The issue has been corrected. Thank you for reporting it.
