### ISSUE TITLE
.c source changed to .cpp - gcc interprets file differently

### ISSUE THREAD

**Issue by tonywmnix** [hebaishi/linter-gcc#35]
Hi, 
this package seems to be copying my .c source file to /tmp/ with an extension of .cpp. 
My older gcc-4.6 is interpreting this file differently depending on the extension. 

*Can the file extension of the source file be preserved?*
thanks

**Comment by hebaishi** [comment]
Thank you for opening the issue. I will fix this issue ASAP and publish a new release.

**Comment by hebaishi** [comment]
Hello. The bug has fixed. Please update to the latest version of linter-gcc. Let me know if if works for you now.

**Comment by tonywmnix** [comment]
Works for me! Thanks.

@hebaishi A comment on a different issue got me thinking. Is it possible to set more than 1 gcc/g++/etc compiler per directory? For example, if the source contained a mix of C,C++,ASM it seems like it would choose single compiler executable.
