### ISSUE TITLE
linter-gcc not working on Mac OS X

### ISSUE THREAD

**Issue by matheusmstos** [hebaishi/linter-gcc#43]
Hi,
I'm new to Atom and I was trying to use linter-gcc on my mac, but I'ts not working on my C file. I've searched  this on google, but I can't find the solution! 

Any help?
Thanks guys

<img width="1280" alt="captura de tela 2016-04-03 as 18 58 56" src="https://cloud.githubusercontent.com/assets/18218843/14235229/23fbf2b6-f9ce-11e5-810e-c92f1c2f95bd.png">

**Comment by keplersj** [comment]
It looks like your Mac doesn't have GCC installed, but rather clang. I'd recommend trying [`linter-clang`](https://atom.io/packages/linter-clang).

**Comment by matheusmstos** [comment]
Oh, so simple! It worked! Thank you som much! 
Just curiosity: what's the main difference between clang and gcc?

**Comment by keplersj** [comment]
This [pape](http://clang.llvm.org/comparison.html) from the LLVM may be worth reading.

It's also worth noting that clang and the LLVM are essentially run out of Apple, which is why clang is built into your Mac.
