### ISSUE TITLE
Linter can't find <iostream>, but g++ can

### ISSUE THREAD

**Issue by branden-akana** [hebaishi/linter-gcc#57]
## Checklist
* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14

## Issue (including debugging messages):

Windows user here.

The linter is giving me an error on this very basic program that it can't find `<iostream>`.
My GCC Executable Path is `C:\MinGW\bin\g++.exe`.
Using that very same path to compile my program using the commandline (`g++ main.cpp`) works perfectly.

Any help is appreciated.

![](http://i.imgur.com/yK7guLd.png)

**Comment by charozard** [comment]
I'm having a very similar issue and have adjusted my path/executable path per suggestion. Do you mind sharing your solution to the problem if you found one?
