### ISSUE TITLE
Linter Gcc not working

### ISSUE THREAD

**Issue by pankajk0001** [hebaishi/linter-gcc#66]
I have all the 3 requirements to run linter gcc but not able to run .

## Issue (including debugging messages):
Linter gcc not working 
![ss1](https://cloud.githubusercontent.com/assets/17299085/16079985/07a40a2e-3324-11e6-955c-2c12215c65eb.png)
![ss2](https://cloud.githubusercontent.com/assets/17299085/16079986/07adb330-3324-11e6-8550-9bc0c6cbf06f.png)

**Comment by hebaishi** [comment]
`g++` needs to be in your `$PATH`, like it says in the GCC Executable Path description. Also, on Windows, your executable path should be just `g++`. This is so that g++ can find its libraries.

**Comment by hebaishi** [comment]
Please let me know when you have managed to get it working.

**Comment by pankajk0001** [comment]
Now GCC is not working in CMD too.

**Comment by pankajk0001** [comment]
Fixed 
Thank You very much you are doing a great job.
