### ISSUE TITLE
 lint on-th-fly generate a "c" file in the temp folder.

### ISSUE THREAD

**Issue by mickey9910326** [hebaishi/linter-gcc#70]
## Checklist
* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14

I just got a error when open lint on-th-fly.
When a bug in the file, it will generate a "c" file in the temp folder.
windows 8.10 has the smae bug (I haven't test on w7 )
sorry  for my poor English,hope you can understand

## Issue (including debugging messages):
![bug](https://cloud.githubusercontent.com/assets/10437920/16546846/4d076588-418a-11e6-82a3-3958aeab4715.jpg)

**Comment by hebaishi** [comment]
This is not an issue. This is simply the way linter-gcc works when lint on-the-fly is enabled. It generates a temporary file, compiles the file with GCC and gets the errors back. When you type into the atom editor, the temporary file gets updated, and the errors as well. The other way to do this would be to pipe the file to linter-gcc, but creating a temporary file is a simpler method that is guaranteed to work on all platforms.

If you do not need lint on-the-fly, or you don't want any temporary files to be generated, simply disable linting on-the-fly in the configuration page. That way, linting will only take place when you save your source file, and no temporary files are needed.
