### ISSUE TITLE
Linter-gcc shows issues with ctdio and cstdlib library

### ISSUE THREAD

**Issue by nilabja10201992** [hebaishi/linter-gcc#80]
## Checklist
![screenshot 18](https://cloud.githubusercontent.com/assets/17797160/18450836/45f06da8-7952-11e6-822d-ee67cbca4224.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/17797160/18450851/52eed990-7952-11e6-8587-edfa7b69c8cb.png)

Linter-gcc is showing error in library files....

please help me.. Thank You

* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14
* [x] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by hebaishi** [comment]
This is not a linter-gcc issue but a problem with your code. You need to find out in which header file those functions are declared and include that header file.
