### ISSUE TITLE
Feature Request - automatic .gcc-flags.json generation from CMakeFiles

### ISSUE THREAD

**Issue by artivis** [hebaishi/linter-gcc#84]
## Checklist
- [x] Check that you have the GNU C Compiler installed by typing `gcc --version` into a terminal.
- [x] If you don't have the `linter` package installed, either update to the latest version of `linter-gcc` or install linter directly with `apm install linter`.
- [x] Ensure that you are using a valid grammar - either C/C++/C++14
- [x] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.
## Issue (including debugging messages):

Hi,
a bit of context, I am working with large cpp project with a root CMakeFiles, subdirectories and sub-CMakeFiles...
it would be great to have an option or such to automatically generate the `.gcc-flags.json` config file directly from those CMakeFiles. Looking around I didn't see anything like that.

Thanks for sharing your work !

Cheers.

**Comment by hebaishi** [comment]
Hello. Thank you for your interest! This feature has already been implemented. I just need to write some tests for it and I'll publish it in the next version of linter-gcc.

**Comment by artivis** [comment]
Wow great ! Looking forward to it.
Cheers.

**Comment by agarciamontoro** [comment]
This would be awesome for large projects. Need any help with those tests?

**Comment by hebaishi** [comment]
Please update to the latest version of linter-gcc to use this new feature.

**Comment by agarciamontoro** [comment]
Awesome, thank you! :)
