### ISSUE TITLE
Update CSS selector for linter gutter element

### ISSUE THREAD

**Issue by steelbrain** [hebaishi/linter-gcc#9]
`.icon-right::before` css selector will be replaced by `.linter-gutter` of the new linter gutter element.

For more details: https://github.com/atom-community/linter/issues/906

**Comment by hebaishi** [comment]
Thanks for the heads up! linter-gcc doesn't use custom message types or any of the APIs that have been deprecated. I can confirm it's working with the latest version of linter. Thanks for the amazing work!

**Comment by steelbrain** [comment]
Are you sure it works with the master branch? Those changes haven't been released yet

**Comment by hebaishi** [comment]
I have just had a look at your changelog, and linter-gcc doesn't use any of the APIs you are deprecating. You have the go-ahead from me.

**Comment by steelbrain** [comment]
Alright then :smiley:
