### ISSUE TITLE
jni.h not found

### ISSUE THREAD

**Issue by chojunki** [hebaishi/linter-gcc#95]
## Checklist
* My GCC is 6.2.0(minGW on windows 10)
* linter-gcc is 0.6.15
* C Source Code is here.

#include <jni.h> 
// This line makes an error. This header file is in "C:\Program Files\Java\jdk1.8.0_111\include"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "CheckIntegrity.h"

// Implementation of native method checkItem() of CheckIntegrity class
JNIEXPORT jstring JNICALL Java_CheckIntegrity_checkItem
  (JNIEnv *env, jobject thisObj, jstring inJNIStr)
{

   // Get a class reference for java.lang.Integer
   jclass cls = NULL;
   jmethodID mtdID = NULL;
   jobject newObj = NULL;

   // Step 1: Convert the JNI String (jstring) into C-String (char*)
   const char *inCStr = (*env)->GetStringUTFChars(env, inJNIStr, NULL);
   if (NULL == inCStr) return NULL;

   // Step 2: Perform its intended operations
   printf("In C, the received string is: %s\n", inCStr);
   (*env)->ReleaseStringUTFChars(env, inJNIStr, inCStr);  // release resources

   // Prompt user for a C-string
   char outCStr[128];
   printf("Enter a Line: ");
   gets(outCStr);    // not more than 127 characters

   if (strcmp(outCStr, inCStr) != 0) {
     printf("Different Strings : %s %s\n", inCStr, outCStr);
     exit(0);
   }
   else {
     printf("Same Strings : %s %s\n", inCStr, outCStr);
   }

   cls = (*env)->FindClass(env, "AnotherFunction");
   if (cls == NULL) {
     printf("Class Not Found");
     exit(0);
   }

   mtdID = (*env)->GetMethodID(env, cls, "printInput", "(Ljava/lang/String;)V");
   if (mtdID == NULL) {
     printf("Method Not Found");
     exit(0);
   }
   newObj = (*env)-> AllocObject(env, cls);
   (*env)->CallObjectMethod(env, newObj, mtdID, inJNIStr);

   // Step 3: Convert the C-string (char*) into JNI String (jstring) and return
   return (*env)->NewStringUTF(env, outCStr);

}

## Issue (including debugging messages):

My log messages are like  belows. I set my configuration to have "C:\Program Files\Java\jdk1.8.0_111\include" and "C:\Program Files\Java\jdk1.8.0_111\include\win32" as additional include path.

The situation is:
1. If I type Ctrl-S to invoke linter-gcc, it says jni.h: No such file or directory at line 1 col 17
2. If I copy the real command from console and try to run it in DOS command prompt, it compiles normally.

I can't solve this problem for now. That is why I raise an issue to you.

linter-gcc: Using configuration page settings

linter-gcc config: {"execPath":"gcc.exe","gccIncludePaths":"\"C:\\Program Files\\Java\\jdk1.8.0_111\\include\",\"C:\\Program Files\\Java\\jdk1.8.0_111\\include\\win32\"","gccSuppressWarnings":false,"gccDefaultCFlags":"-c -Wall -fsyntax-only","gccDefaultCppFlags":"-c -Wall -std=c++11 -fsyntax-only","gccErrorLimit":0,"gccErrorString":"error","gccWarningString":"warning","gccNoteString":"note"}

linter-gcc: C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe -c -Wall -fsyntax-only -fmax-errors=0 -I"C:\Program Files\Java\jdk1.8.0_111\include" -I"C:\Program Files\Java\jdk1.8.0_111\include\win32" D:\test\CheckIntegrity.c

**Comment by chojunki** [comment]
I think this problem is related to System Policy, which does not allow ordinary programs to do something in Program Files Directory to make it possible to clean up windows itself without clean-install. Atom seems to search some virtual store and jni.h is not there.  I came to this conclusion and just copied original Java include directory to C;\jni_dev, which worked. I want to know what has really happened while trying to access C:\Program Files\Java\jdk1.8.0_111\include\jni.h.

**Comment by hebaishi** [comment]
You can turn on the debugging option of linter-gcc, then open the Developer Console by pressing ```Ctrl+Shift+I``` or ```Cmd+Shift+I```, then clicking on 'Console'. All linter-gcc config and the entire command should be visible in the console.
