### ISSUE TITLE
Is it possible to force exec linter-gcc during typing or with timer?

### ISSUE THREAD

**Issue by xdevelnet** [hebaishi/linter-gcc#96]
Hi!

I decided to throw away proprietary Clion and turn Atom into something similar.

So, I found your plugin. Compared to linter-clang, your plugin works! Thanks a lot! :smile:

Unfortunately, it's working only when I'm saving file, but not on-fly. Is it possible to force execution of linter-gcc during typing or after some events/timers? Is you plugin working by passing all code to gcc and then parsing output? 

OS: Debian 8 64bit
GCC: 4.9.2-10
CLANG: 3.5.0-10

Best wishes, Xdevelnet.

**Comment by isgj** [comment]
Go to settings of linter-gcc and select on the fly option
![schermata del 2016-12-08 12-46-38](https://cloud.githubusercontent.com/assets/20517048/21008970/811a8572-bd44-11e6-967d-511b7b9740f2.png)
